<?php
/*
Accents retirés sur 1ère lettre pour ces pays : (pour tri, sinon on les retrouve à la fin de la liste)
-------------- fr
"Aland (Îles)"
"Egypte"
"Emirats arabes unis"
"Equateur"
"Erythrée"
"Etats-Unis d'Amérique"
"Ethiopie"
"Ile de Man"
"Iles mineures éloignées des États-Unis"

-------------- en
"Aland Islands"
*/
$pays = array(
array(4, 'AF', 'AFG', 'Afghanistan', 'Afghanistan'),
array(248, 'AX', 'ALA', 'Aland Islands', 'Aland (Îles)'),
array(8, 'AL', 'ALB', 'Albania', 'Albanie'),
array(12, 'DZ', 'DZA', 'Algeria', 'Algérie'),
array(16, 'AS', 'ASM', 'American Samoa', 'Samoa américaines'),
array(20, 'AD', 'AND', 'Andorra', 'Andorre'),
array(24, 'AO', 'AGO', 'Angola', 'Angola'),
array(660, 'AI', 'AIA', 'Anguilla', 'Anguilla'),
array(10, 'AQ', 'ATA', 'Antarctica', 'Antarctique'),
array(28, 'AG', 'ATG', 'Antigua and Barbuda', 'Antigua-et-Barbuda'),
array(32, 'AR', 'ARG', 'Argentina', 'Argentine'),
array(51, 'AM', 'ARM', 'Armenia', 'Arménie'),
array(533, 'AW', 'ABW', 'Aruba', 'Aruba'),
array(36, 'AU', 'AUS', 'Australia', 'Australie'),
array(40, 'AT', 'AUT', 'Austria', 'Autriche'),
array(31, 'AZ', 'AZE', 'Azerbaijan', 'Azerbaïdjan'),
array(44, 'BS', 'BHS', 'Bahamas', 'Bahamas'),
array(48, 'BH', 'BHR', 'Bahrain', 'Bahreïn'),
array(50, 'BD', 'BGD', 'Bangladesh', 'Bangladesh'),
array(52, 'BB', 'BRB', 'Barbados', 'Barbade'),
array(112, 'BY', 'BLR', 'Belarus', 'Bélarus'),
array(56, 'BE', 'BEL', 'Belgium', 'Belgique'),
array(84, 'BZ', 'BLZ', 'Belize', 'Belize'),
array(204, 'BJ', 'BEN', 'Benin', 'Bénin'),
array(60, 'BM', 'BMU', 'Bermuda', 'Bermudes'),
array(64, 'BT', 'BTN', 'Bhutan', 'Bhoutan'),
array(68, 'BO', 'BOL', 'Bolivia (Plurinational State of)', 'Bolivie (État plurinational de)'),
array(535, 'BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Saint-Eustache et Saba'),
array(70, 'BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine'),
array(72, 'BW', 'BWA', 'Botswana', 'Botswana'),
array(74, 'BV', 'BVT', 'Bouvet Island', 'Bouvet (Île)'),
array(76, 'BR', 'BRA', 'Brazil', 'Brésil'),
array(86, 'IO', 'IOT', 'British Indian Ocean Territory', 'Indien (Territoire britannique de océan)'),
array(96, 'BN', 'BRN', 'Brunei Darussalam', 'Brunéi Darussalam'),
array(100, 'BG', 'BGR', 'Bulgaria', 'Bulgarie'),
array(854, 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso'),
array(108, 'BI', 'BDI', 'Burundi', 'Burundi'),
array(132, 'CV', 'CPV', 'Cabo Verde', 'Cabo Verde'),
array(116, 'KH', 'KHM', 'Cambodia', 'Cambodge'),
array(120, 'CM', 'CMR', 'Cameroon', 'Cameroun'),
array(124, 'CA', 'CAN', 'Canada', 'Canada'),
array(136, 'KY', 'CYM', 'Cayman Islands', 'Caïmans (Îles)'),
array(140, 'CF', 'CAF', 'Central African Republic', 'République centrafricaine'),
array(148, 'TD', 'TCD', 'Chad', 'Tchad'),
array(152, 'CL', 'CHL', 'Chile', 'Chili'),
array(156, 'CN', 'CHN', 'China', 'Chine'),
array(162, 'CX', 'CXR', 'Christmas Island', 'Christmas (Île)'),
array(166, 'CC', 'CCK', 'Cocos (Keeling) Islands', 'Cocos (Îles) / Keeling (Îles)'),
array(170, 'CO', 'COL', 'Colombia', 'Colombie'),
array(174, 'KM', 'COM', 'Comoros', 'Comores'),
array(180, 'CD', 'COD', 'Congo (the Democratic Republic of the)', 'Congo (République démocratique du)'),
array(178, 'CG', 'COG', 'Congo', 'Congo'),
array(184, 'CK', 'COK', 'Cook Islands', 'Cook (Îles)'),
array(188, 'CR', 'CRI', 'Costa Rica', 'Costa Rica'),
array(384, 'CI', 'CIV', 'Côte d\'Ivoire', 'Côte d\'Ivoire'),
array(191, 'HR', 'HRV', 'Croatia', 'Croatie'),
array(192, 'CU', 'CUB', 'Cuba', 'Cuba'),
array(531, 'CW', 'CUW', 'Curaçao', 'Curaçao'),
array(196, 'CY', 'CYP', 'Cyprus', 'Chypre'),
array(203, 'CZ', 'CZE', 'Czechia', 'Tchéquie'),
array(208, 'DK', 'DNK', 'Denmark', 'Danemark'),
array(262, 'DJ', 'DJI', 'Djibouti', 'Djibouti'),
array(212, 'DM', 'DMA', 'Dominica', 'Dominique'),
array(214, 'DO', 'DOM', 'Dominican Republic', 'dominicaine (République)'),
array(218, 'EC', 'ECU', 'Ecuador', 'Equateur'),
array(818, 'EG', 'EGY', 'Egypt', 'Egypte'),
array(222, 'SV', 'SLV', 'El Salvador', 'El Salvador'),
array(226, 'GQ', 'GNQ', 'Equatorial Guinea', 'Guinée équatoriale'),
array(232, 'ER', 'ERI', 'Eritrea', 'Erythrée'),
array(233, 'EE', 'EST', 'Estonia', 'Estonie'),
array(231, 'ET', 'ETH', 'Ethiopia', 'Ethiopie'),
array(238, 'FK', 'FLK', 'Falkland Islands [Malvinas]', 'Falkland (Îles) / Malouines (Îles)'),
array(234, 'FO', 'FRO', 'Faroe Islands', 'Féroé (Îles)'),
array(242, 'FJ', 'FJI', 'Fiji', 'Fidji'),
array(246, 'FI', 'FIN', 'Finland', 'Finlande'),
array(250, 'FR', 'FRA', 'France', 'France'),
array(254, 'GF', 'GUF', 'French Guiana', 'Guyane française'),
array(258, 'PF', 'PYF', 'French Polynesia', 'Polynésie française'),
array(260, 'TF', 'ATF', 'French Southern Territories', 'Terres austrafrançaises'),
array(266, 'GA', 'GAB', 'Gabon', 'Gabon'),
array(270, 'GM', 'GMB', 'Gambia', 'Gambie'),
array(268, 'GE', 'GEO', 'Georgia', 'Géorgie'),
array(276, 'DE', 'DEU', 'Germany', 'Allemagne'),
array(288, 'GH', 'GHA', 'Ghana', 'Ghana'),
array(292, 'GI', 'GIB', 'Gibraltar', 'Gibraltar'),
array(300, 'GR', 'GRC', 'Greece', 'Grèce'),
array(304, 'GL', 'GRL', 'Greenland', 'Groenland'),
array(308, 'GD', 'GRD', 'Grenada', 'Grenade'),
array(312, 'GP', 'GLP', 'Guadeloupe', 'Guadeloupe'),
array(316, 'GU', 'GUM', 'Guam', 'Guam'),
array(320, 'GT', 'GTM', 'Guatemala', 'Guatemala'),
array(831, 'GG', 'GGY', 'Guernsey', 'Guernesey'),
array(324, 'GN', 'GIN', 'Guinea', 'Guinée'),
array(624, 'GW', 'GNB', 'Guinea-Bissau', 'Guinée-Bissau'),
array(328, 'GY', 'GUY', 'Guyana', 'Guyana'),
array(332, 'HT', 'HTI', 'Haiti', 'Haïti'),
array(334, 'HM', 'HMD', 'Heard Island and McDonald Islands', 'Heard-et-MacDonald (Île)'),
array(336, 'VA', 'VAT', 'Holy See', 'Saint-Siège'),
array(340, 'HN', 'HND', 'Honduras', 'Honduras'),
array(344, 'HK', 'HKG', 'Hong Kong', 'Hong Kong'),
array(348, 'HU', 'HUN', 'Hungary', 'Hongrie'),
array(352, 'IS', 'ISL', 'Iceland', 'Islande'),
array(356, 'IN', 'IND', 'India', 'Inde'),
array(360, 'ID', 'IDN', 'Indonesia', 'Indonésie'),
array(364, 'IR', 'IRN', 'Iran (Islamic Republic of)', 'Iran (République Islamique d\')'),
array(368, 'IQ', 'IRQ', 'Iraq', 'Iraq'),
array(372, 'IE', 'IRL', 'Ireland', 'Irlande'),
array(833, 'IM', 'IMN', 'Isle of Man', 'Ile de Man'),
array(376, 'IL', 'ISR', 'Israel', 'Israël'),
array(380, 'IT', 'ITA', 'Italy', 'Italie'),
array(388, 'JM', 'JAM', 'Jamaica', 'Jamaïque'),
array(392, 'JP', 'JPN', 'Japan', 'Japon'),
array(832, 'JE', 'JEY', 'Jersey', 'Jersey'),
array(400, 'JO', 'JOR', 'Jordan', 'Jordanie'),
array(398, 'KZ', 'KAZ', 'Kazakhstan', 'Kazakhstan'),
array(404, 'KE', 'KEN', 'Kenya', 'Kenya'),
array(296, 'KI', 'KIR', 'Kiribati', 'Kiribati'),
array(408, 'KP', 'PRK', 'Korea (the Democratic People\'s Republic of)', 'Corée (République populaire démocratique de)'),
array(410, 'KR', 'KOR', 'Korea (the Republic of)', 'Corée (République de)'),
array(414, 'KW', 'KWT', 'Kuwait', 'Koweït'),
array(417, 'KG', 'KGZ', 'Kyrgyzstan', 'Kirghizistan'),
array(418, 'LA', 'LAO', 'Lao People\'s Democratic Republic', 'Lao, République démocratique populaire'),
array(428, 'LV', 'LVA', 'Latvia', 'Lettonie'),
array(422, 'LB', 'LBN', 'Lebanon', 'Liban'),
array(426, 'LS', 'LSO', 'Lesotho', 'Lesotho'),
array(430, 'LR', 'LBR', 'Liberia', 'Libéria'),
array(434, 'LY', 'LBY', 'Libya', 'Libye'),
array(438, 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein'),
array(440, 'LT', 'LTU', 'Lithuania', 'Lituanie'),
array(442, 'LU', 'LUX', 'Luxembourg', 'Luxembourg'),
array(446, 'MO', 'MAC', 'Macao', 'Macao'),
array(807, 'MK', 'MKD', 'Macedonia (the former Yugoslav Republic of)', 'Macédoine (ex-République yougoslave de)'),
array(450, 'MG', 'MDG', 'Madagascar', 'Madagascar'),
array(454, 'MW', 'MWI', 'Malawi', 'Malawi'),
array(458, 'MY', 'MYS', 'Malaysia', 'Malaisie'),
array(462, 'MV', 'MDV', 'Maldives', 'Maldives'),
array(466, 'ML', 'MLI', 'Mali', 'Mali'),
array(470, 'MT', 'MLT', 'Malta', 'Malte'),
array(584, 'MH', 'MHL', 'Marshall Islands', 'Marshall (Îles)'),
array(474, 'MQ', 'MTQ', 'Martinique', 'Martinique'),
array(478, 'MR', 'MRT', 'Mauritania', 'Mauritanie'),
array(480, 'MU', 'MUS', 'Mauritius', 'Maurice'),
array(175, 'YT', 'MYT', 'Mayotte', 'Mayotte'),
array(484, 'MX', 'MEX', 'Mexico', 'Mexique'),
array(583, 'FM', 'FSM', 'Micronesia (Federated States of)', 'Micronésie (États fédérés de)'),
array(498, 'MD', 'MDA', 'Moldova (the Republic of)', 'Moldova (République de)'),
array(492, 'MC', 'MCO', 'Monaco', 'Monaco'),
array(496, 'MN', 'MNG', 'Mongolia', 'Mongolie'),
array(499, 'ME', 'MNE', 'Montenegro', 'Monténégro'),
array(500, 'MS', 'MSR', 'Montserrat', 'Montserrat'),
array(504, 'MA', 'MAR', 'Morocco', 'Maroc'),
array(508, 'MZ', 'MOZ', 'Mozambique', 'Mozambique'),
array(104, 'MM', 'MMR', 'Myanmar', 'Myanmar'),
array(516, 'NA', 'NAM', 'Namibia', 'Namibie'),
array(520, 'NR', 'NRU', 'Nauru', 'Nauru'),
array(524, 'NP', 'NPL', 'Nepal', 'Népal'),
array(528, 'NL', 'NLD', 'Netherlands', 'Pays-Bas'),
array(540, 'NC', 'NCL', 'New Caledonia', 'Nouvelle-Calédonie'),
array(554, 'NZ', 'NZL', 'New Zealand', 'Nouvelle-Zélande'),
array(558, 'NI', 'NIC', 'Nicaragua', 'Nicaragua'),
array(562, 'NE', 'NER', 'Niger', 'Niger'),
array(566, 'NG', 'NGA', 'Nigeria', 'Nigéria'),
array(570, 'NU', 'NIU', 'Niue', 'Niue'),
array(574, 'NF', 'NFK', 'Norfolk Island', 'Norfolk (Île)'),
array(580, 'MP', 'MNP', 'Northern Mariana Islands', 'Mariannes du Nord (Îles)'),
array(578, 'NO', 'NOR', 'Norway', 'Norvège'),
array(512, 'OM', 'OMN', 'Oman', 'Oman'),
array(586, 'PK', 'PAK', 'Pakistan', 'Pakistan'),
array(585, 'PW', 'PLW', 'Palau', 'Palaos'),
array(275, 'PS', 'PSE', 'Palestine, State of', 'Palestine, État de'),
array(591, 'PA', 'PAN', 'Panama', 'Panama'),
array(598, 'PG', 'PNG', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée'),
array(600, 'PY', 'PRY', 'Paraguay', 'Paraguay'),
array(604, 'PE', 'PER', 'Peru', 'Pérou'),
array(608, 'PH', 'PHL', 'Philippines', 'Philippines'),
array(612, 'PN', 'PCN', 'Pitcairn', 'Pitcairn'),
array(616, 'PL', 'POL', 'Poland', 'Pologne'),
array(620, 'PT', 'PRT', 'Portugal', 'Portugal'),
array(630, 'PR', 'PRI', 'Puerto Rico', 'Porto Rico'),
array(634, 'QA', 'QAT', 'Qatar', 'Qatar'),
array(638, 'RE', 'REU', 'Réunion', 'Réunion'),
array(642, 'RO', 'ROU', 'Romania', 'Roumanie'),
array(643, 'RU', 'RUS', 'Russian Federation', 'Russie (Fédération de)'),
array(646, 'RW', 'RWA', 'Rwanda', 'Rwanda'),
array(652, 'BL', 'BLM', 'Saint Barthélemy', 'Saint-Barthélemy'),
array(654, 'SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'Sainte-Hélène, Ascension et Tristan da Cunha'),
array(659, 'KN', 'KNA', 'Saint Kitts and Nevis', 'Saint-Kitts-et-Nevis'),
array(662, 'LC', 'LCA', 'Saint Lucia', 'Sainte-Lucie'),
array(663, 'MF', 'MAF', 'Saint Martin (French part)', 'Saint-Martin (partie française)'),
array(666, 'PM', 'SPM', 'Saint Pierre and Miquelon', 'Saint-Pierre-et-Miquelon'),
array(670, 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-Grenadines'),
array(882, 'WS', 'WSM', 'Samoa', 'Samoa'),
array(674, 'SM', 'SMR', 'San Marino', 'Saint-Marin'),
array(678, 'ST', 'STP', 'Sao Tome and Principe', 'Sao Tomé-et-Principe'),
array(682, 'SA', 'SAU', 'Saudi Arabia', 'Arabie saoudite'),
array(686, 'SN', 'SEN', 'Senegal', 'Sénégal'),
array(688, 'RS', 'SRB', 'Serbia', 'Serbie'),
array(690, 'SC', 'SYC', 'Seychelles', 'Seychelles'),
array(694, 'SL', 'SLE', 'Sierra Leone', 'Sierra Leone'),
array(702, 'SG', 'SGP', 'Singapore', 'Singapour'),
array(534, 'SX', 'SXM', 'Sint Maarten (Dutch part)', 'Saint-Martin (partie néerlandaise)'),
array(703, 'SK', 'SVK', 'Slovakia', 'Slovaquie'),
array(705, 'SI', 'SVN', 'Slovenia', 'Slovénie'),
array(90, 'SB', 'SLB', 'Solomon Islands', 'Salomon (Îles)'),
array(706, 'SO', 'SOM', 'Somalia', 'Somalie'),
array(710, 'ZA', 'ZAF', 'South Africa', 'Afrique du Sud'),
array(239, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'Géorgie du Sud-et-les Îles Sandwich du Sud'),
array(728, 'SS', 'SSD', 'South Sudan', 'Soudan du Sud'),
array(724, 'ES', 'ESP', 'Spain', 'Espagne'),
array(144, 'LK', 'LKA', 'Sri Lanka', 'Sri Lanka'),
array(729, 'SD', 'SDN', 'Sudan', 'Soudan'),
array(740, 'SR', 'SUR', 'Suriname', 'Suriname'),
array(744, 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard et Île Jan Mayen'),
array(748, 'SZ', 'SWZ', 'Swaziland', 'Swaziland'),
array(752, 'SE', 'SWE', 'Sweden', 'Suède'),
array(756, 'CH', 'CHE', 'Switzerland', 'Suisse'),
array(760, 'SY', 'SYR', 'Syrian Arab Republic', 'République arabe syrienne'),
array(158, 'TW', 'TWN', 'Taiwan (Province of China)', 'Taïwan (Province de Chine)'),
array(762, 'TJ', 'TJK', 'Tajikistan', 'Tadjikistan'),
array(834, 'TZ', 'TZA', 'Tanzania, United Republic of', 'Tanzanie, République-Unie de'),
array(764, 'TH', 'THA', 'Thailand', 'Thaïlande'),
array(626, 'TL', 'TLS', 'Timor-Leste', 'Timor-Leste'),
array(768, 'TG', 'TGO', 'Togo', 'Togo'),
array(772, 'TK', 'TKL', 'Tokelau', 'Tokelau'),
array(776, 'TO', 'TON', 'Tonga', 'Tonga'),
array(780, 'TT', 'TTO', 'Trinidad and Tobago', 'Trinité-et-Tobago'),
array(788, 'TN', 'TUN', 'Tunisia', 'Tunisie'),
array(792, 'TR', 'TUR', 'Turkey', 'Turquie'),
array(795, 'TM', 'TKM', 'Turkmenistan', 'Turkménistan'),
array(796, 'TC', 'TCA', 'Turks and Caicos Islands', 'Turks-et-Caïcos (Îles)'),
array(798, 'TV', 'TUV', 'Tuvalu', 'Tuvalu'),
array(800, 'UG', 'UGA', 'Uganda', 'Ouganda'),
array(804, 'UA', 'UKR', 'Ukraine', 'Ukraine'),
array(784, 'AE', 'ARE', 'United Arab Emirates', 'Emirats arabes unis'),
array(826, 'GB', 'GBR', 'United Kingdom of Great Britain and Northern Irela', 'Royaume-Uni de Grande-Bretagne et d\'Irlande du Nord'),
array(581, 'UM', 'UMI', 'United States Minor Outlying Islands', 'Iles mineures éloignées des États-Unis'),
array(840, 'US', 'USA', 'United States of America', 'Etats-Unis d\'Amérique'),
array(858, 'UY', 'URY', 'Uruguay', 'Uruguay'),
array(860, 'UZ', 'UZB', 'Uzbekistan', 'Ouzbékistan'),
array(548, 'VU', 'VUT', 'Vanuatu', 'Vanuatu'),
array(862, 'VE', 'VEN', 'Venezuela (Bolivarian Republic of)', 'Venezuela (République bolivarienne du)'),
array(704, 'VN', 'VNM', 'Viet Nam', 'Viet Nam'),
array(92, 'VG', 'VGB', 'Virgin Islands (British)', 'Vierges britanniques (Îles)'),
array(850, 'VI', 'VIR', 'Virgin Islands (U.S.)', 'Vierges des États-Unis (Îles)'),
array(876, 'WF', 'WLF', 'Wallis and Futuna', 'Wallis-et-Futuna '),
array(732, 'EH', 'ESH', 'Western Sahara', 'Sahara occidental'),
array(887, 'YE', 'YEM', 'Yemen', 'Yémen'),
array(894, 'ZM', 'ZMB', 'Zambia', 'Zambie'),
array(716, 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwe'),
);